### ISSUE TITLE
install third-party software for Lubuntu

### ISSUE THREAD

**Issue by candrapersada** [lubuntu-team/calamares-settings-ubuntu#6]
how to install third-party software alternatives for lubuntu?
![lubuntu install](https://user-images.githubusercontent.com/36833664/75099891-83857280-55f9-11ea-845c-9faaa8c87ed7.PNG)

**Comment by wxl** [comment]
First off, thanks for your interest in Lubuntu! I'm still not entirely sure if you're a user of it, a flavor or derivative user, or a developer of either, but I guess we've got your attention regardless so we must be doing *something* right :wink: 

Secondly, I notice you've been making heavy use of GitHub issues and we don't use them like *at all* :rofl: so I thought it would be reasonable to point out a couple resources we **do** use.

For matters of reporting bugs, which functionality doesn't appear to be working correctly or if there's a feature you feel is missing, there's a canonical (lower case c, not to be confused with the company behind Ubuntu) process to do it which we have [documented](https://phab.lubuntu.me/w/bugs/) on our [Phabricator instance](https://phab.lubuntu.me), which we use for project management. If you do it this way, it will have the added advantage of getting more eyes on it (basically it's visible to the entire Ubuntu community) rather than just being our small little team.

For discussion of any kind, we have [IRC/Telegram/Matrix and mailing lists](https://lubuntu.me/links/), but you might like our [Discourse instance](https://discourse.lubuntu.me/), which has proven incredibly popular. This is a great place not only to ask for help with something you don't understand, but it's also a great place to ask questions about how things are supposed to work. Thus, it's a perfect place to do research before reporting bugs so you can describe them well.

And yes, I'm basically saying don't use GitHub issues at all. These repos exist primarily to allow for people to make pull requests if they're not comfortable with our usual way of doing things.

Finally, and more to your point, [we're working on it](https://phab.lubuntu.me/T68). The linked bug report has some workarounds.

Again, thanks, and if you have further questions, you now know where to find us :smile:
